spring:

  datasource:
      url: jdbc:h2:mem:test
      username: sa
      password: secret

  rabbitmq:
    address: localhost
    host: localhost
    port: 8010
    username: guest
    password: guest