spring:

  datasource:
      url: jdbc:h2:mem:test
      username: sa
      password: secret

  rabbitmq:
    address: localhost
    port: 8010
    username: guest
    password: guest

  provider:
    external:
      token-uri: http://localhost:8090/login