server:
  port: ${PORT}

spring:
  datasource:
    # H2 database configuration.
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: secret

  # H2 database console configuration.
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true




  jpa:
    spring.jpa.database-platform:org.hibernate.dialect.H2Dialect

  rabbitmq:
    queues:
      messages:
        name: messagesQueue
        durable: true
      callback:
        name: callBackQueue
        durable: true
    exchanges:
      messages:
        name: messagesExchange
        durable: true
        autoDelete: false
    bindings:
      routingKey: messages
